icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome5"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
[block.theme_overrides]
idle_bg = "#D8DEE9"
idle_fg = "#A0A6B2"

[[block]]
block = "custom"
command = "whoami"
interval = "once"
[block.theme_overrides]
idle_bg = "#A0A6B2"
idle_fg = "#D8DEE9"

[[block]]
block = "custom"
command = "cat /etc/hostname"
interval = "once"
[block.theme_overrides]
idle_bg = "#A0A6B2"
idle_fg = "#D8DEE9"

[[block]]
block = "custom"
command = "echo `uname` `uname -r | tr - . | cut -d. -f1-2`"
interval = "once"
[block.theme_overrides]
idle_bg = "#A0A6B2"
idle_fg = "#D8DEE9"
